name: 手动构建镜像到阿里云ACR

# 仅版本号在此修改，其余全部读取 GitHub 配置
env:
  CUSTOM_VERSION: "v0.3.42.0"

# 仅手动点击触发
on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      # 🔥 唯一操作：临时屏蔽测试命令，构建完成后无效，不修改你的源码
      - name: 临时跳过测试（仅构建使用）
        run: |
          sed -i '22s/^/#/' Dockerfile

      - name: 登录阿里云镜像仓库
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_CR_REGISTRY }}
          username: ${{ secrets.ALIYUN_CR_USERNAME }}
          password: ${{ secrets.ALIYUN_CR_PASSWORD }}

      - name: 构建并推送标准镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          # 固定构建官方标准镜像，和官方完全一致，数据库无问题
          target: standard
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.ALIYUN_CR_REGISTRY }}/${{ secrets.ALIYUN_CR_REPO }}:${{ env.CUSTOM_VERSION }}
            ${{ secrets.ALIYUN_CR_REGISTRY }}/${{ secrets.ALIYUN_CR_REPO }}:latest
